import { DefaultTheme } from 'styled-components/native';

export const Theme: DefaultTheme = {
  colors: {
    gray01: '#FFFFFF',
    gray02: '#F9F9FA',
    gray03: '#D9D9D9',
    gray04: '#BCBCBE',
    gray05: '#929292',
    gray06: '#767676',
    gray07: '#5C5C5C',
    gray08: '#383838',
    gray09: '#2E2E2E',
    gray10: '#202020',
    gray11: '#000000',
  },
  gradients: {
    button: {
      colors: ['#BFF0F5', '#E0D9FF'],
      start: { x: 0, y: 0 },
      end: { x: 1, y: 0 },
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  typography: {
    fontSizes: {
      small: 12,
      medium: 16,
      large: 20,
      xlarge: 24,
    },
    fontWeights: {
      regular: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
    },
    fonts: {
      pretendard: {
        thin: 'Pretendard-Thin',
        extralight: 'Pretendard-ExtraLight',
        light: 'Pretendard-Light',
        regular: 'Pretendard-Regular',
        medium: 'Pretendard-Medium',
        semibold: 'Pretendard-SemiBold',
        bold: 'Pretendard-Bold',
        black: 'Pretendard-Black',
        extrabold: 'Pretendard-ExtraBold',
      },
      inter: {
        variable: 'InterVariable',
        thin: 'Inter-Thin',
        thinItalic: 'Inter-ThinItalic',
        extralight: 'Inter-ExtraLight',
        extralightItalic: 'Inter-ExtraLightItalic',
        light: 'Inter-Light',
        lightItalic: 'Inter-LightItalic',
        regular: 'Inter-Regular',
        italic: 'Inter-Italic',
        medium: 'Inter-Medium',
        mediumItalic: 'Inter-MediumItalic',
        semibold: 'Inter-SemiBold',
        semiboldItalic: 'Inter-SemiBoldItalic',
        bold: 'Inter-Bold',
        boldItalic: 'Inter-BoldItalic',
        extrabold: 'Inter-ExtraBold',
        extraboldItalic: 'Inter-ExtraBoldItalic',
        black: 'Inter-Black',
        blackItalic: 'Inter-BlackItalic',
      },
    },
  },
  radius: {
    small: 4,
    medium: 8,
    large: 16,
    round: 9999,
  },
};
